sonar.projectKey=SatisTalepYonetimi
sonar.projectName=Satış Talep Yönetimi
sonar.projectVersion=1.0

# Source
sonar.sources=SatisTalepYonetimi/
sonar.tests=Test/
sonar.language=cs

# Encoding
sonar.sourceEncoding=UTF-8

# Exclusions
sonar.exclusions=**/Migrations/**,**/bin/**,**/obj/**,**/wwwroot/**
sonar.test.exclusions=**/bin/**,**/obj/**

# Coverage
sonar.cs.opencover.reportsPaths=**/TestResults/**/coverage.opencover.xml

# Duplication
sonar.cpd.minimumTokens=50
